### ISSUE TITLE
Different package for user presence?

### ISSUE THREAD

**Issue by Neobii** [copleykj/socialize-user-presence#11]
What about switching to this more maintained package for user presence? https://github.com/mizzao/meteor-user-status/

**Comment by copleykj** [comment]
What is less maintained about this package? Less popular, or less features I guess maybe. This package is also is more extensible AND works with multiple servers. The ticket for multiple servers on meteor-user-status has been open for 2 years and is no closer to solving the issue. https://github.com/mizzao/meteor-user-status/issues/21

**Comment by Neobii** [comment]
Gotcha, well then I'll work on taking mizzao status out of my app then and
use your package only :)
