### ISSUE TITLE
No userId in connection object

### ISSUE THREAD

**Issue by kizim** [copleykj/socialize-user-presence#12]
I'm trying to use onSessionConnected method on server side, but there is no userId field in connection object.

Connection object:

```
{ 
  id: 'fc3LM2KyNs2GTvNo7',
  close: [Function: close],
  onClose: [Function: onClose],
  clientAddress: '127.0.0.1',
  httpHeaders: { 
    'x-forwarded-for': '127.0.0.1',
    'x-forwarded-proto': 'ws',
    host: 'localhost:3000',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50' 
  } 
}
```

How can I get userId for connection?
Thanks.

**Comment by copleykj** [comment]
Unfortunately the connection doesn't have the userId.. I'll see what I can do about getting an update out that passes the userId as the second parameter.

**Comment by alexnault** [comment]
```
UserPresence.onSessionConnected(function(connection) {
	Sessions.insert({
		_id: connection.id,
		userId: Meteor.userId(),
	});
});
```

This works for me. Any drawbacks to using `Meteor.userId()`?
