### ISSUE TITLE
[Question] Support for React

### ISSUE THREAD

**Issue by bilicio** [copleykj/socialize-user-presence#17]
Hi Kelly, this work with React too or only React-Native?

thank you!

**Comment by copleykj** [comment]
Hi Phillipe, the package is front end agnostic. Just to clarify though, in case you found this package via NPM, this is a Meteor.js package and the server specific code must be run within a Meteor application.

**Comment by bilicio** [comment]
Thank you Kelly! yep, i found your comment on the meteor forum (https://forums.meteor.com/t/track-online-offline-of-a-user/41616/4), my app uses meteor, and im looking for a solution to lock some pages if a user is seeing them, and when the user log off or disconnects the page become free for another person. So, i can use your package web based cant i?

**Comment by copleykj** [comment]
Sorry I didn't get back to you sooner on this..

If you are looking to lock certain pages in your app, I'm not sure that this will fit your usecase.. This package basically keeps track of all the sessions of the users that are connected to your app and gives you the knowledge if they are online or not.

**Comment by bilicio** [comment]
Yeah! I know... When the user open the page I will track the session connection of the user and which page the user is seeing , than when he disconnects I will free the spot to another person.  I think this will work. :)

**Comment by copleykj** [comment]
:+1:
