### ISSUE TITLE
onUserOffline is not working

### ISSUE THREAD

**Issue by shkomg** [copleykj/socialize-user-presence#2]
Hi,

onUserOffline not fires up. I've just added it like this on server:

```
UserPresence.onUserOnline(function(userId){                                                                                                                                               
    Meteor.users.update({_id:userId}, {$set:{'profile.status':"online"}})                                                                                                                 
});                                                                                                                                                                                       

UserPresence.onUserOffline(function(userId){                                                                                                                                              
console.log(userId);                                                                                                                                                                      
    Meteor.users.update({_id:userId}, {$set:{'profile.status':"offline"}})                                                                                                                
});                                                                                                                                                                                       

```

onUserOnline - work fine. 
But on Offline - nothing happens. Console.log not works too.

Any suggestions?

Thank you.

**Comment by dan335** [comment]
I thought it wasn't working at first too.  My problem was that I had multiple browser windows open.  Closing just one didn't fire the offline callback.  Make sure all windows are closed.  It's working for me.

**Comment by copleykj** [comment]
I believe there may actually be a bug in the server presence package that is causing this. When running the app locally using meteor the app doesn't receive a term signal because the signal is received by the meteor command instead. To deal with this server presence uses a bit of a complicated process to check for servers going down. I believe the bug lies in this logic, I just haven't had the time to evaluate the issue.

**Comment by shkomg** [comment]
np, I've done that without the use of socialize packages.
Thank you for your response.

2016-01-15 16:44 GMT+02:00 Kelly Copley notifications@github.com:

> I believe there may actually be a bug in the server presence package that
> is causing this. When running the app locally using meteor the app doesn't
> receive a term signal because the signal is received by the meteor command
> instead. To deal with this server presence uses a bit of a complicated
> process to check for servers going down. I believe the bug lies in this
> logic, I just haven't had the time to evaluate the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/copleykj/socialize-user-presence/issues/2#issuecomment-171978587
> .

## 

Best regards

Serhiy Khvashchuk

**Comment by copleykj** [comment]
server presence package is now fixed, so this should now work properly.
