### ISSUE TITLE
Incompatible with Meteor 2.3

### ISSUE THREAD

**Issue by diavrank** [copleykj/socialize-user-presence#21]
Issue [here](https://github.com/meteor/meteor/issues/11453#issuecomment-862663009)

**Comment by copleykj** [comment]
update should be coming sometime today.

**Comment by diavrank** [comment]
@copleykj any news about this?

**Comment by copleykj** [comment]
Sorry, updates can have a cascade effect when you have a dependency tree such as with this set of packages and so I tend to release updates for all the packages at once. Releases should be coming shortly.

**Comment by copleykj** [comment]
Done

**Comment by diavrank** [comment]
Thank you so much! I have just updated to 2.3 and now it works perfectly.
