### ISSUE TITLE
Best way to keep track of where the user is using FlowRouter?

### ISSUE THREAD

**Issue by nadeemja** [copleykj/socialize-user-presence#7]
Hi,

What is the most sensible way to track user-presence per route? 

Thanks,

**Comment by copleykj** [comment]
I would think that would depend on your specific use case. This package is more meant to track the fact that you users are online across multiple sessions on multiple servers, and clean up neatly if a server instance ends abruptly. It currently does not implement tracking user activity across the app.

**Comment by nadeemja** [comment]
Ok, thanks for the reply.

My use case is very simple. 

I have routes like this: /schedules/IdOfSchedule

All I want to do is filter presence by "idOfSchedule".

Can it be done?

**Comment by copleykj** [comment]
I don't believe it can currently be done. You can always for and modify the package for your needs. I'll also accept PRs for any sensible additions.

**Comment by copleykj** [comment]
Also there is a slack group at https://meteor-socialize.slack.com in case you have more questions.
