### ISSUE TITLE
Undefined connection.userId

### ISSUE THREAD

**Issue by creitz** [copleykj/socialize-user-presence#8]
In 

UserPresence.onSessionConnected(function(connection){
    var userId = connection.userId;
});

run on the server, userId is always undefined. Any idea why?

Thanks!

**Comment by creitz** [comment]
connection.id also seems to be null, but connection looks like it is simply an id

**Comment by copleykj** [comment]
You are right.. I will get a fix on this asap.

**Comment by creitz** [comment]
Awesome, thanks!

**Comment by copleykj** [comment]
fixed in 0.4.0
