### ISSUE TITLE
ReferenceError: determineStatus is not defined

### ISSUE THREAD

**Issue by ibrahimzahoor** [copleykj/socialize-user-presence#9]
Client: `Error: invoking Method 'updateSessionStatus': Internal server error [500]`
Server: `ReferenceError: determineStatus is not defined`
when we call  `Meteor.user().setStatusOnline();`
because determineStatus is not globally defined.

**Comment by copleykj** [comment]
Thanks for the PR! I'll have a closer look at this later tonight and merge then.
